// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pixelix.API.Data;

#nullable disable

namespace Pixelix.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128003836_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0b44ca04-f6b0-4a8f-a953-1f2330d30894",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            RoleId = "0b44ca04-f6b0-4a8f-a953-1f2330d30894"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pixelix.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .HasMaxLength(26)
                        .HasColumnType("varchar(26)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Animais"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Blocos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Cenários"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Comidas"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Itens"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Personagens"
                        });
                });

            modelBuilder.Entity("Pixelix.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Qtde")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Pack de animais para montar sua fazendinha em pixel art.",
                            Destaque = true,
                            Foto = "/img/categorias/animais/1/pack-fazendinha.jpeg",
                            Nome = "Pack Fazendinha",
                            Qtde = 10,
                            ValorCusto = 0m,
                            ValorVenda = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descricao = "Pack de gatinhos fofinhos em pixel art.",
                            Destaque = true,
                            Foto = "/img/categorias/animais/2/pack-gatinhos.jpeg",
                            Nome = "Pack Gatinhos",
                            Qtde = 10,
                            ValorCusto = 0m,
                            ValorVenda = 5.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descricao = "Pack de passarinhos em pixel art.",
                            Destaque = true,
                            Foto = "/img/categorias/animais/3/pack-passaros.jpeg",
                            Nome = "Pack Pássaros",
                            Qtde = 10,
                            ValorCusto = 0m,
                            ValorVenda = 5.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descricao = "Pack de animais silvestres em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/animais/4/pack/silvestre.jpeg",
                            Nome = "Pack de Animais Silvestres",
                            Qtde = 10,
                            ValorCusto = 0m,
                            ValorVenda = 5.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descricao = "Pack de diversas flores em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/blocos/1/pack-blocoflores.jpeg",
                            Nome = "Pack de Blocos de Flores",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            Descricao = "Pack de blocos de elementos em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/blocos/2/pack-blocoseslementos.jpeg",
                            Nome = "Pack de Blocos e Elementos",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Descricao = "Pack de grama em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/blocos/3/pack-blocosgrama.jpeg",
                            Nome = "Pack de Blocos de Grama",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Descricao = "Sprite de portal mágico para seu jogo.",
                            Destaque = false,
                            Foto = "/img/categorias/blocos/4/portal.jpeg",
                            Nome = "Portal Mágico",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            Descricao = "Cenário em pixel art do jogo CoinQuest.",
                            Destaque = false,
                            Foto = "/img/categorias/cenarios/1/cenario-coinquest.jpeg",
                            Nome = "Cenário Completo CoinQuest",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 3,
                            Descricao = "Cenário em pixel art do desenho Hora de Aventura.",
                            Destaque = false,
                            Foto = "/img/categorias/cenarios/2/cenario-horadeaventura.jpeg",
                            Nome = "Cenário Completo de Hora de Aventura",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 3,
                            Descricao = "Cenário em pixel art do desenho Mystery Hack.",
                            Destaque = false,
                            Foto = "/img/categorias/cenarios/3/cenario-mysteryhack.jpeg",
                            Nome = "Cenário Completo de Mystery Hack",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 4,
                            Descricao = "Pack de comidas 2D + de 130 sprites deliciosos!.",
                            Destaque = false,
                            Foto = "/img/categorias/comidas/1/pack-comidas.jpeg",
                            Nome = "Pack de Comidas Diversas",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 4,
                            Descricao = "Pack de doces e sobremesas 2D + de 130 sprites deliciosos!.",
                            Destaque = false,
                            Foto = "/img/categorias/comidas/2/pack-doces.jpeg",
                            Nome = "Pack de Doces Diversos",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 5,
                            Descricao = "Pack de poções mágicas em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/itens/1/pack-pocoes.jpeg",
                            Nome = "Pack de Poções",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem fada em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/1/fadinha-frente.jpeg",
                            Nome = "Pack de Fadinha",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem globin em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/2/globin-frente.jpeg",
                            Nome = "Pack de Globin",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem mago em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/3/mago-frente.jpeg",
                            Nome = "Pack de Mago",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem feminina em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/4/menina-frente.jpeg",
                            Nome = "Pack de Personagem Feminina",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem masculino em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/5/menino-frente.jpeg",
                            Nome = "Pack de Personagem Masculino",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem vilão em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/6/vilao-frente.jpeg",
                            Nome = "Pack de Vilão",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem bruxa em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/7/pack-bruxas.jpeg",
                            Nome = "Pack Bruxa Pixel Art",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 6,
                            Descricao = "Pack de personagem fadinhas em pixel art.",
                            Destaque = false,
                            Foto = "/img/categorias/personagens/8/pack-fadinhas.jpeg",
                            Nome = "Pack Fadinhas Pixel Art",
                            Qtde = 5,
                            ValorCusto = 0m,
                            ValorVenda = 8.99m
                        });
                });

            modelBuilder.Entity("Pixelix.API.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ddf093a6-6cb5-4ff7-9a64-83da34aee005",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e679a0ba-4522-4824-b172-9b62b993c126",
                            DataNascimento = new DateTime(2006, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taynasuperti@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/avatar.png",
                            LockoutEnabled = true,
                            Nome = "Tayná Carolina Miguel Superti",
                            NormalizedEmail = "TAYNASUPERTI@GMAIL.COM",
                            NormalizedUserName = "TAYNASUPERTI@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMJvVcRjKBfMnatcEgG4k3eroRazNuSeyTeGeI8f+2XH0bGlhETfIMHf8EJPgpOMNA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f4e1b60-7626-4ab8-8ffb-d50bd867b117",
                            TwoFactorEnabled = false,
                            UserName = "taynasuperti@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pixelix.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pixelix.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pixelix.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pixelix.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pixelix.API.Models.Produto", b =>
                {
                    b.HasOne("Pixelix.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
